### ISSUE TITLE
如何配置代理信息

### ISSUE THREAD

**Issue by Ccnavi** [vacuityv/vacproxy#2]
如何配置代理信息 需要指定 ip和端口吗
看到了鉴权

**Comment by vacuityv** [comment]
@Ccnavi  这个东西本身提供的是转发服务，假设你要从A访问C，然后A不能直达C，然后B可以访问C，A可以访问B，这个时候就可以把这个部署到B上，然后在A上通过B访问C

**Comment by Ccnavi** [comment]
好的 这个是一个服务端对吧 那我理解错了

**Comment by vacuityv** [comment]
@Ccnavi  可以这么说

**Comment by Ccnavi** [comment]
好的 晚些试用一下 star了

**Comment by vacuityv** [comment]
@Ccnavi  感谢，如有问题欢迎再次反馈
