### ISSUE TITLE
配置好服务后服务日志飙升，服务建立之后就结束

### ISSUE THREAD

**Issue by Ccnavi** [vacuityv/vacproxy#3]
debian12

go1.20.1 amd64

➜  vacproxy tac vacproxy.log| head -5
2024/02/26 18:04:54 server.go:131: server terminated
2024/02/26 18:04:54 conn.go:92: 7167821822568697858-begin tunnel
2024/02/26 18:04:54 conn.go:73: 7167821822568697858-server connect 172.19.6.123:33474 to 47.xx.xx.xx:7777
2024/02/26 18:04:54 conn.go:182: 7167821819729154048-end tunnel
可以帮我看下 什么问题不 这个是部署在b端的 

a机器：大陆机器无法访问github
b机器：可以访问github
c端：github

就是这么个情况 在a端建立连接后 b端服务日志 一直再跑持续上面字段 

a端终端打印
rroot@debian12-test:~# wget -i --proxy http://47.xx.xx.xx:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 18:02:03--  http://47.xx.xx.xx:7777
Connecting to 47.xx.xx.xx:7777... connected.
HTTP request sent, awaiting response... ^C

**Comment by vacuityv** [comment]
@Ccnavi  看日志像是链接断开了，你测试下直接在b上运行wget会不会有问题，然后试下我在release编译好的包

**Comment by Ccnavi** [comment]
b端使用wget没问题

a机器
root@debian12-test:~# wget -i --proxy http://47.xx.xx.xx:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 18:48:39--  http://47.xx.xx.xx:7777/
Connecting to 47.xx.xx.xx:7777... connected.
HTTP request sent, awaiting response... ^C
b端使用你编译好的 也同样是跟上面一样
➜  cs tac vacproxy.log | head -5
2024/02/26 18:49:00 conn.go:182: 7167832914258825216-end tunnel
2024/02/26 18:49:00 conn.go:43: 7167832921053597696-connecting to 47.xx.xx.xx:7777
2024/02/26 18:49:00 conn.go:35: 7167832921053597696-client connect 47.xx.xx.xx:43402 to 172.19.6.123:7777
2024/02/26 18:49:00 conn.go:182: 7167832914246242304-end tunnel
2024/02/26 18:49:00 conn.go:92: 7167832921045209088-begin tunnel

看下

**Comment by vacuityv** [comment]
你用下这个的7777端口试试 43.198.242.23在 2024年2月26日，18:56，Ccnavi ***@***.***> 写道：﻿
b端使用wget没问题
a机器
***@***.***:~# wget -i --proxy http://47.xx.xx.xx:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 18:48:39--  http://47.xx.xx.xx:7777/
Connecting to 47.xx.xx.xx:7777... connected.
HTTP request sent, awaiting response... ^C
b端使用你编译好的 也同样是跟上面一样
➜  cs tac vacproxy.log | head -5
2024/02/26 18:49:00 conn.go:182: 7167832914258825216-end tunnel
2024/02/26 18:49:00 conn.go:43: 7167832921053597696-connecting to 47.xx.xx.xx:7777
2024/02/26 18:49:00 conn.go:35: 7167832921053597696-client connect 47.xx.xx.xx:43402 to 172.19.6.123:7777
2024/02/26 18:49:00 conn.go:182: 7167832914246242304-end tunnel
2024/02/26 18:49:00 conn.go:92: 7167832921045209088-begin tunnel
看下

**Comment by Ccnavi** [comment]
> 你用下这个的7777端口试试 43.198.242.23在 2024年2月26日，18:56，Ccnavi ***@***.***> 写道：﻿ b端使用wget没问题 a机器 ***@***.***:~# wget -i --proxy http://47.xx.xx.xx:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz --2024-02-26 18:48:39-- http://47.xx.xx.xx:7777/ Connecting to 47.xx.xx.xx:7777... connected. HTTP request sent, awaiting response... ^C b端使用你编译好的 也同样是跟上面一样 ➜ cs tac vacproxy.log | head -5 2024/02/26 18:49:00 conn.go:182: 7167832914258825216-end tunnel 2024/02/26 18:49:00 conn.go:43: 7167832921053597696-connecting to 47.xx.xx.xx:7777 2024/02/26 18:49:00 conn.go:35: 7167832921053597696-client connect 47.xx.xx.xx:43402 to 172.19.6.123:7777 2024/02/26 18:49:00 conn.go:182: 7167832914246242304-end tunnel 2024/02/26 18:49:00 conn.go:92: 7167832921045209088-begin tunnel 看下 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

root@debian12-test:~# wget -i --proxy http://43.198.242.23:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 19:12:13--  http://43.198.242.23:7777/
Connecting to 43.198.242.23:7777... connected.
HTTP request sent, awaiting response...

无响应

**Comment by vacuityv** [comment]
奇怪，我用这个正常，不然你换个网络试试在 2024年2月26日，19:14，Ccnavi ***@***.***> 写道：﻿

你用下这个的7777端口试试 43.198.242.23在 2024年2月26日，18:56，Ccnavi @.> 写道：﻿ b端使用wget没问题 a机器 @.:~# wget -i --proxy http://47.xx.xx.xx:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz --2024-02-26 18:48:39-- http://47.xx.xx.xx:7777/ Connecting to 47.xx.xx.xx:7777... connected. HTTP request sent, awaiting response... ^C b端使用你编译好的 也同样是跟上面一样 ➜ cs tac vacproxy.log | head -5 2024/02/26 18:49:00 conn.go:182: 7167832914258825216-end tunnel 2024/02/26 18:49:00 conn.go:43: 7167832921053597696-connecting to 47.xx.xx.xx:7777 2024/02/26 18:49:00 conn.go:35: 7167832921053597696-client connect 47.xx.xx.xx:43402 to 172.19.6.123:7777 2024/02/26 18:49:00 conn.go:182: 7167832914246242304-end tunnel 2024/02/26 18:49:00 conn.go:92: 7167832921045209088-begin tunnel 看下 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

***@***.***:~# wget -i --proxy http://43.198.242.23:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 19:12:13--  http://43.198.242.23:7777/
Connecting to 43.198.242.23:7777... connected.
HTTP request sent, awaiting response...
无响应

**Comment by Ccnavi** [comment]
> 奇怪，我用这个正常，不然你换个网络试试在 2024年2月26日，19:14，Ccnavi ***@***.***> 写道：﻿ 你用下这个的7777端口试试 43.198.242.23在 2024年2月26日，18:56，Ccnavi @.> 写道：﻿ b端使用wget没问题 a机器 @.:~# wget -i --proxy http://47.xx.xx.xx:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz --2024-02-26 18:48:39-- http://47.xx.xx.xx:7777/ Connecting to 47.xx.xx.xx:7777... connected. HTTP request sent, awaiting response... ^C b端使用你编译好的 也同样是跟上面一样 ➜ cs tac vacproxy.log | head -5 2024/02/26 18:49:00 conn.go:182: 7167832914258825216-end tunnel 2024/02/26 18:49:00 conn.go:43: 7167832921053597696-connecting to 47.xx.xx.xx:7777 2024/02/26 18:49:00 conn.go:35: 7167832921053597696-client connect 47.xx.xx.xx:43402 to 172.19.6.123:7777 2024/02/26 18:49:00 conn.go:182: 7167832914246242304-end tunnel 2024/02/26 18:49:00 conn.go:92: 7167832921045209088-begin tunnel 看下 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> ***@***.***:~# wget -i --proxy http://43.198.242.23:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz --2024-02-26 19:12:13-- http://43.198.242.23:7777/ Connecting to 43.198.242.23:7777... connected. HTTP request sent, awaiting response... 无响应 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

我换个大陆服务器试试

**Comment by Ccnavi** [comment]
root@VM-16-5-debian:~# wget -i --proxy http://43.198.242.23:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 19:36:11--  http://43.198.242.23:7777/
Connecting to 43.198.242.23:7777... connected.
HTTP request sent, awaiting response... 

还是不行 换个一个

**Comment by vacuityv** [comment]
奇怪，我也没招了，不然你试试这个工具吧： snail007/goproxy at vacuity.megithub.com在 2024年2月26日，19:37，Ccnavi ***@***.***> 写道：﻿
***@***.***:~# wget -i --proxy http://43.198.242.23:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz
--2024-02-26 19:36:11--  http://43.198.242.23:7777/
Connecting to 43.198.242.23:7777... connected.
HTTP request sent, awaiting response...
还是不行 换个一个

**Comment by Ccnavi** [comment]
> 奇怪，我也没招了，不然你试试这个工具吧： snail007/goproxy at vacuity.megithub.com在 2024年2月26日，19:37，Ccnavi ***@***.***> 写道：﻿ ***@***.***:~# wget -i --proxy http://43.198.242.23:7777 https://github.com/navidrome/navidrome/releases/download/v0.51.1/navidrome_0.51.1_linux_amd64.tar.gz --2024-02-26 19:36:11-- http://43.198.242.23:7777/ Connecting to 43.198.242.23:7777... connected. HTTP request sent, awaiting response... 还是不行 换个一个 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

谢谢 你看下 我刚才测试 你服务器有没有日志

**Comment by vacuityv** [comment]
好像没看到

**Comment by Ccnavi** [comment]
> 好像没看到

是不是网卡有内网ip导致的一直死循环 你的机器是什么样的 有内网不
